namespace Mohamad.ToDo.Api.Configuration
{
    //class responsible for dto-s
    public class AuthResult
    {
        //generated by us
        public string Token { get; set; } = string.Empty;
        public string RefreshToken { get; set; } = string.Empty;
        public bool Success { get; set; }
        public List<string> Errors { get; set; } = [];
    }
}
